# Set PS1 similar to Haiku /etc/profile, but using zsh syntax
_ARCH=`getarch 2>/dev/null`
if [ "$_ARCH" = "`getarch -p 2>/dev/null`" ] ; then
	PS1="%~"
else
	PS1="[$_ARCH] %~"
fi
unset _ARCH

export PS1="%(?.%F{green}.%F{red})$PS1%f> "

