#!/bin/sh

#
# Copyright 2011, Haiku, Inc. All Rights Reserved.
# Distributed under the terms of the MIT License.
#

find $(finddir B_COMMON_DEVEOP_DIRECTORY/headers -type f -print0 | xargs -0 egrep "$@"

# TODO add other header directories to search?
