#!/usr/bin/env bash

: "${PKG_CONFIG_LIBDIR:=$(findpaths -c: B_FIND_PATH_DEVELOP_LIB_DIRECTORY pkgconfig):$(findpaths -c: B_FIND_PATH_DATA_DIRECTORY pkgconfig)}"
: "${PKG_CONFIG_SYSTEM_INCLUDE_PATH:=$(findpaths -c: B_FIND_PATH_HEADERS_DIRECTORY)}"
: "${PKG_CONFIG_SYSTEM_LIBRARY_PATH:=$(findpaths -c: B_FIND_PATH_DEVELOP_LIB_DIRECTORY):$(findpaths -c: B_FIND_PATH_LIB_DIRECTORY)}"

export PKG_CONFIG_LIBDIR PKG_CONFIG_SYSTEM_INCLUDE_PATH PKG_CONFIG_SYSTEM_LIBRARY_PATH

${0##*/}-x86 "$@"
