target_os = "haiku"
target_cpu = "x64"

is_debug = false
is_official_build = true
is_component_build = true

cc = "clang"
cxx = "clang++"

skia_use_gl = true
skia_use_egl = false
skia_use_vulkan = false
skia_use_angle = false

skia_enable_ganesh = true
skia_enable_graphite = true

skia_use_freetype = true
skia_use_system_freetype2 = true

skia_use_system_libpng = true
skia_use_system_libjpeg_turbo = true
skia_use_system_libwebp = true
skia_use_system_zlib = true

skia_enable_fontmgr_fontconfig = true

skia_enable_svg = true
skia_enable_skottie = true
skia_enable_skparagraph = true

skia_enable_tools = false
skia_enable_tests = false
skia_use_dawn = false

extra_cflags = [
  "-fPIC",
]

extra_ldflags = [
  "-fPIC",
]

extra_cflags_cc = [
  "-std=c++20",
]
