#!/bin/sh

libDir=`finddir B_SYSTEM_LIB_DIRECTORY`

# Determine which GCC we're running
if [ -f "$libDir"/libsupc++.so ] ; then
	HAIKU_GCC_VERSION=4
else
	HAIKU_GCC_VERSION=2
fi

SETGCC_OUTPUT=`setgcc`
CURRENT_COMPILER=${SETGCC_OUTPUT: -1:1}

if [ $CURRENT_COMPILER == $HAIKU_GCC_VERSION ] ; then
	libdir=`finddir B_COMMON_LIB_DIRECTORY`
else
	libdir=`finddir B_COMMON_LIB_DIRECTORY`/gcc$CURRENT_COMPILER
fi

prefix=/boot/common
exec_prefix=${prefix}
exec_prefix_set=no

#usage="\
#Usage: sdl-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"
usage="\
Usage: sdl-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs] [--static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.2.15
      ;;
    --cflags)
      echo -I${prefix}/include/SDL -D_GNU_SOURCE=1
      ;;
#    --libs)
#      echo -L$libdir  -lSDL 
#      ;;
#    --static-libs)
    --libs|--static-libs)
      echo -L$libdir  -lSDL   -liconv -lGL -lroot -lbe -lmedia -lgame -ldevice -ltextencoding
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
