diff --git a/SRC/Makefile b/SRC/Makefile
index 12029bd..cce9963 100644
--- a/SRC/Makefile
+++ b/SRC/Makefile
@@ -32,8 +32,8 @@ OSFLAG=
 #		choose either of a) b) or c)
 #
 # a) if you use termcap, enable the following lines
-TFLAG=-DM_TERMCAP
-TLIB=termcap
+#TFLAG=-DM_TERMCAP
+#TLIB=termcap
 
 # b) if you are using terminfo on a XENIX machine, enable the following lines
 #TFLAG=-DM_TERMINFO
@@ -41,8 +41,8 @@ TLIB=termcap
 
 # c) if you use terminfo on any other type of machine,
 #    enable the following lines
-#TFLAG=-DM_TERMINFO
-#TLIB=curses
+TFLAG=-DM_TERMINFO
+TLIB=ncurses
 
 #
 #	3) SELECTION OF WINDOW MANAGER AVAILABILITY
@@ -73,6 +73,7 @@ CFILES= spiff.c output.c compare.c float.c strings.c exact.c miller.c parse.c co
 HFILES=misc.h strings.h line.h float.h floatrep.h tol.h command.h comment.h token.h edit.h parse.h compare.h flagdefs.h exact.h miller.h visual.h output.h
 OTHER=README Makefile Sample.1 Sample.2 Sample.3 Sample.4 paper.ms paper.out
 MANPAGE=spiff.1
+INSDIR=insDir
 
 CFLAGS=-O $(OSFLAG) $(TFLAG) $(VISFLAG)
 
@@ -138,6 +139,7 @@ cpio:
 cmd:
 	-$(CMD) $(CFILES) $(HFILES) $(OTHER) $(MANPAGE)
 install:
-	mv spiff $(INSDIR)/bin
+	mkdir -p $(INSDIR)/man/man1
+	mv spiff $(INSDIR)
 	cp $(MANPAGE) $(INSDIR)/man/man1
 	
